name: cljds
description: ClojureDart project generation made using ClojureDart. Supports plain Dart and Flutter project.
version: 1.2.0
homepage: https://github.com/ampersanda/clojuredart-cli

environment:
  sdk: '>=2.18.0-edge.572f24882f2c344f9f95b14091a7ac2cb142f9de <3.0.0'

executables:
  cljds:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  http: ^0.13.5
  mason_logger: ^0.2.4
