name: cljds
description: ClojureDart project generation made using ClojureDart. Supports plain Dart and Flutter project.
version: 1.1.2
homepage: https://github.com/ampersanda/clojuredart-cli

environment:
  sdk: '>=2.17.3 <3.0.0'

executables:
  cljds:

dev_dependencies:
  analyzer: ^3.3.1
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  http: ^0.13.5
