name: cljds
description: ClojureDart project generation made using ClojureDart. Supports plain Dart and Flutter project.
version: 2.2.2
homepage: https://github.com/ampersanda/clojuredart-cli

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  cljds:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

dependencies:
  args: ^2.4.0
  http: ^1.2.0
  mason_logger: ^0.3.0
