(ns cljds.generators.dart
  (:require
    [cljds.consts :refer [dart-docs-url]]
    [cljds.utils.log :refer [info]]
    [cljds.utils.names :as names]
    [cljds.generators.core :as gen]))

(defn generate
  "Generate a plain Dart ClojureDart project."
  [project-name opts]
  (let [success (await (gen/generate-project project-name :dart opts))]
    (when success
      (let [{:keys [dir]} (names/names project-name)
            dir-name (names/resolve-dir project-name (:output opts))]
        (info
          ""
          "To run:"
          (str "  $ cd " dir-name)
          (str "  $ clj -M:cljd compile && dart run bin/" dir ".dart")
          ""
          (str "Read more: " dart-docs-url))))))
