(ns cljds.generators.flutter
  (:require
    [cljds.consts :refer [flutter-docs-url]]
    [cljds.utils.log :refer [info]]
    [cljds.utils.names :as names]
    [cljds.generators.core :as gen]))

(defn generate
  "Generate a Flutter ClojureDart project."
  [project-name opts]
  (let [success (await (gen/generate-project project-name :flutter opts))]
    (when success
      (let [dir-name (names/resolve-dir project-name (:output opts))]
        (info
          ""
          "To run:"
          (str "  $ cd " dir-name)
          "  $ clj -M:cljd flutter"
          ""
          (str "Read more: " flutter-docs-url))))))
