(ns cljds.consts)

(def version "2.2.1")

(def dart-docs-url
  "https://github.com/Tensegritics/ClojureDart/blob/main/doc/quick-start.md")

(def flutter-docs-url
  "https://github.com/Tensegritics/ClojureDart/blob/main/doc/flutter-quick-start.md")

(def sha-url
  (.parse Uri "https://raw.githubusercontent.com/Tensegritics/ClojureDart/main/.hashes"))

(def fallback-sha
  "8d5916c0dc87146dc2e8921aaa7fd5dc3c6c3401")
